# Random Forest Regression

## Importing the libraries

In [97]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [98]:
dataset = pd.read_csv('ecommerce_customer_data.csv')
X = dataset.iloc[ : , :-1].values
y = dataset.iloc[ : , -1].values
print(X)
print(y)

[[56 'Male' 41672 11]
 [46 'Female' 78217 9]
 [32 'Female' 28279 10]
 ...
 [27 'Female' 45709 11]
 [61 'Male' 66514 10]
 [19 'Male' 79375 4]]
[170.75  63.17  55.09 110.88 158.37  31.15 123.83  41.46  26.56  29.49
 170.15  41.24  28.13  98.82 171.92  67.23  95.91  27.19 100.83 123.97
 122.76  79.84  76.8   39.19  86.02  37.91 157.99 193.93 194.61 175.71
 128.14 146.16  71.34 133.54 102.02 106.76 156.4   70.75  77.25 186.44
  30.12 107.41 184.3  129.87 118.35  64.95  81.79 173.37 120.66 112.65
  37.92  22.89 193.46  87.86 128.58  34.35 142.96 187.86 123.62  42.7
 124.71 157.94  93.15 178.37 136.76 181.86 132.23  43.63  75.74  56.32
 183.59 156.87 141.75  74.17  53.13 156.16 105.35  60.64 130.99  27.26
  78.71 104.34  46.63 197.24  57.64  43.46  56.64 158.43  96.59 121.77
  23.78  26.2  100.25 167.   179.34  35.61 116.91 184.38  89.84 169.32
  44.07 188.37 155.26 189.44 141.79  85.41 188.87  69.6   79.79 146.15
 157.76 187.29  56.86 163.64 152.94  31.48  89.7   70.9   74.81 196.93
 135.7 

## Encoding data

### Encoding the Binary Independent Variable

In [99]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1]= le.fit_transform((X[:,1]))

In [100]:
print(X)

[[56 1 41672 11]
 [46 0 78217 9]
 [32 0 28279 10]
 ...
 [27 0 45709 11]
 [61 1 66514 10]
 [19 1 79375 4]]


In [101]:
Y=[]
for i in y:
    if i>100:
        Y.append("High")
    else:
        Y.append("Low")

In [102]:
print(Y)

['High', 'Low', 'Low', 'High', 'High', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'Low', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'High', 'High', 'High', 'Low', 'High', 'High', 'High', 'High', 'Low', 'Low', 'High', 'Low', 'High', 'High', 'High', 'High', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'Low', 'High', 'Low', 'High', 'Low', 'High', 'High', 'High', 'Low', 'High', 'High', 'Low', 'High', 'High', 'High', 'High', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'Low', 'High', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'High', 'High', 'Low', 'High', 'Low', 'High', 'High', 'High', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'High', 'High', 'Low', 'High', 'High', 'Low', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'High', 'Low', 'High', 'Low', 'High', 'Low', 'High', 'Low', 'Low', 'High', 'Lo

In [103]:
Y= le.fit_transform(Y)
print(Y)

[0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1
 1 0 0 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 1 0 0
 0 1 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 1 1 1 0 1 1 1 1 0 0 1 0
 0 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1
 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 0 1 0
 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1 0 0 0 0 1
 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1
 1 1 1 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 1 1 1
 1 1 0 1 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 1 0 0 0 0 1 0 0
 0 1 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1
 0 1 1 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 0 1 0 1 0 1
 1 0 1 0 0 0 0 0 1 0 0 0 

## Splitting the dataset into the Training set and Test set

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [105]:
print(X_train)

[[28 0 26442 8]
 [36 0 80862 11]
 [41 0 52968 10]
 ...
 [48 1 45933 8]
 [37 1 68938 17]
 [25 0 47292 12]]


In [106]:
print(y_train)

[0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1
 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1
 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 1
 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 1 0 0 1 1
 0 1 0 0 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0
 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0 1 1 1 1 1 0 0 1 0 1 0 1 0
 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1
 0 1 0 0 1 0 0 1 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 1 1 0 1
 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0
 1 1 0 1 0 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 1
 1 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1 0 1
 0 0 0 1 0 1 1 1 1 1 0 0 

In [107]:
print(X_test)

[[23 1 53588 10]
 [43 1 70106 10]
 [53 1 64458 11]
 [40 1 44005 15]
 [31 1 40310 5]
 [61 0 44992 10]
 [61 1 56851 4]
 [50 0 84364 7]
 [24 0 75165 11]
 [46 1 35673 13]
 [41 0 80843 9]
 [34 1 27115 12]
 [31 1 41970 8]
 [36 0 62801 12]
 [52 0 51326 8]
 [64 0 32624 14]
 [42 1 32844 9]
 [45 1 34401 13]
 [41 1 77699 13]
 [31 1 59527 12]
 [45 1 69937 4]
 [27 1 58343 9]
 [29 1 44313 8]
 [39 0 46946 9]
 [31 0 63452 13]
 [55 1 60641 12]
 [31 0 21656 8]
 [34 0 59707 11]
 [21 1 58800 4]
 [46 0 78217 9]
 [33 0 22540 7]
 [23 1 50363 6]
 [46 1 40966 8]
 [55 1 57696 5]
 [54 1 44177 7]
 [18 0 35010 9]
 [37 0 56360 10]
 [44 0 63786 11]
 [53 0 64541 9]
 [22 0 58287 13]
 [33 1 12508 9]
 [40 1 12045 10]
 [43 1 45780 15]
 [53 0 51017 7]
 [57 1 70880 9]
 [38 0 62711 10]
 [60 1 65015 10]
 [32 0 57155 11]
 [55 0 50511 19]
 [59 1 59462 8]
 [52 1 51140 11]
 [52 0 48052 10]
 [33 1 40979 16]
 [54 0 51793 10]
 [64 0 47598 9]
 [53 1 39247 5]
 [52 1 51834 13]
 [26 1 51878 10]
 [28 0 40687 7]
 [44 1 26661 11]
 [26 0 5

In [108]:
print(y_test)

[1 1 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 0 1 0 0
 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 1 0 1 0 0 1 0 1 1 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 0 1 0 0 0
 0 1 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0
 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1
 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0
 1 0 0 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1]


## Training the Random Forest Classification model on the Training set

In [109]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42,max_depth=5)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=10,
                       random_state=42)

## Predicting a new result

In [110]:
print(classifier.predict(np.array([[23,1,53588,10]])))

[0]


## Predicting the Test set results

In [111]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]

## Making the Confusion Matrix

In [112]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[103  47]
 [ 76  24]]


0.508