# Random Forest Classification

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Mall_Customers.csv')
X = dataset.iloc[:, 1:-2].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['Male' 19 15]
 ['Male' 21 15]
 ['Female' 20 16]
 ['Female' 23 16]
 ['Female' 31 17]
 ['Female' 22 17]
 ['Female' 35 18]
 ['Female' 23 18]
 ['Male' 64 19]
 ['Female' 30 19]
 ['Male' 67 19]
 ['Female' 35 19]
 ['Female' 58 20]
 ['Female' 24 20]
 ['Male' 37 20]
 ['Male' 22 20]
 ['Female' 35 21]
 ['Male' 20 21]
 ['Male' 52 23]
 ['Female' 35 23]
 ['Male' 35 24]
 ['Male' 25 24]
 ['Female' 46 25]
 ['Male' 31 25]
 ['Female' 54 28]
 ['Male' 29 28]
 ['Female' 45 28]
 ['Male' 35 28]
 ['Female' 40 29]
 ['Female' 23 29]
 ['Male' 60 30]
 ['Female' 21 30]
 ['Male' 53 33]
 ['Male' 18 33]
 ['Female' 49 33]
 ['Female' 21 33]
 ['Female' 42 34]
 ['Female' 30 34]
 ['Female' 36 37]
 ['Female' 20 37]
 ['Female' 65 38]
 ['Male' 24 38]
 ['Male' 48 39]
 ['Female' 31 39]
 ['Female' 49 39]
 ['Female' 24 39]
 ['Female' 50 40]
 ['Female' 27 40]
 ['Female' 29 40]
 ['Female' 31 40]
 ['Female' 49 42]
 ['Male' 33 42]
 ['Female' 31 43]
 ['Male' 59 43]
 ['Female' 50 43]
 ['Male' 47 43]
 ['Female' 51 44]
 ['Male' 69 44]


In [4]:
print(y)

['Average' 'High' 'Low' 'High' 'Average' 'High' 'Low' 'High' 'Low' 'High'
 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Average' 'Average' 'Low' 'High'
 'Average' 'High' 'Low' 'High' 'Low' 'High' 'Average' 'Average' 'Average'
 'High' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Low' 'High' 'Low' 'High'
 'Average' 'High' 'Average' 'Average' 'Low' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Average'
 'Average' 'Average' 'Average' 'Average' 'Average' 'Average' 'Av

## Encoding data

### Encoding the Binary Independent Variable

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
y= le.fit_transform(y)

In [12]:
print(X)

[[1 19 15]
 [1 21 15]
 [0 20 16]
 [0 23 16]
 [0 31 17]
 [0 22 17]
 [0 35 18]
 [0 23 18]
 [1 64 19]
 [0 30 19]
 [1 67 19]
 [0 35 19]
 [0 58 20]
 [0 24 20]
 [1 37 20]
 [1 22 20]
 [0 35 21]
 [1 20 21]
 [1 52 23]
 [0 35 23]
 [1 35 24]
 [1 25 24]
 [0 46 25]
 [1 31 25]
 [0 54 28]
 [1 29 28]
 [0 45 28]
 [1 35 28]
 [0 40 29]
 [0 23 29]
 [1 60 30]
 [0 21 30]
 [1 53 33]
 [1 18 33]
 [0 49 33]
 [0 21 33]
 [0 42 34]
 [0 30 34]
 [0 36 37]
 [0 20 37]
 [0 65 38]
 [1 24 38]
 [1 48 39]
 [0 31 39]
 [0 49 39]
 [0 24 39]
 [0 50 40]
 [0 27 40]
 [0 29 40]
 [0 31 40]
 [0 49 42]
 [1 33 42]
 [0 31 43]
 [1 59 43]
 [0 50 43]
 [1 47 43]
 [0 51 44]
 [1 69 44]
 [0 27 46]
 [1 53 46]
 [1 70 46]
 [1 19 46]
 [0 67 47]
 [0 54 47]
 [1 63 48]
 [1 18 48]
 [0 43 48]
 [0 68 48]
 [1 19 48]
 [0 32 48]
 [1 70 49]
 [0 47 49]
 [0 60 50]
 [0 60 50]
 [1 59 54]
 [1 26 54]
 [0 45 54]
 [1 40 54]
 [0 23 54]
 [0 49 54]
 [1 57 54]
 [1 38 54]
 [1 67 54]
 [0 46 54]
 [0 21 54]
 [1 48 54]
 [0 55 57]
 [0 22 57]
 [0 34 58]
 [0 50 58]
 [0 68 59]

In [13]:
print(y)

[0 1 2 1 0 1 2 1 2 1 2 1 2 1 2 1 0 0 2 1 0 1 2 1 2 1 0 0 0 1 2 1 2 1 2 1 2
 1 2 1 0 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 0 1 2 1 2 1 0 1 2 1 2 1 2 1 2 1 0 1 2 1 0 1
 2 1 2 1 2 1 2 1 2 1 2 1 0 1 2 1 2 1 2 1 2 0 2 1 2 1 2 1 2 0 2 1 0 1 2 1 0
 1 2 0 2 1 2 0 2 1 2 1 2 1 2 1]


## Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
print(X_train)

[[0 47 49]
 [0 23 70]
 [0 41 99]
 [0 27 60]
 [1 34 78]
 [0 54 28]
 [1 60 30]
 [0 56 79]
 [0 65 38]
 [0 51 44]
 [1 39 71]
 [0 47 60]
 [0 32 97]
 [0 35 23]
 [0 38 78]
 [1 48 60]
 [0 50 43]
 [0 31 81]
 [1 33 42]
 [0 55 57]
 [0 35 74]
 [0 68 59]
 [1 32 73]
 [0 49 62]
 [1 25 77]
 [0 50 58]
 [1 66 63]
 [1 37 20]
 [1 35 28]
 [1 32 75]
 [1 28 101]
 [0 50 40]
 [1 19 74]
 [0 35 120]
 [1 68 63]
 [0 67 47]
 [0 20 16]
 [1 53 46]
 [0 44 73]
 [1 32 126]
 [0 31 39]
 [1 67 19]
 [0 47 120]
 [0 60 50]
 [0 45 126]
 [1 59 93]
 [0 30 88]
 [1 43 71]
 [0 40 60]
 [0 38 64]
 [1 34 78]
 [0 32 103]
 [0 49 42]
 [1 19 15]
 [0 32 60]
 [1 65 63]
 [1 24 60]
 [1 63 48]
 [0 33 86]
 [1 24 38]
 [0 32 48]
 [0 31 40]
 [0 29 40]
 [1 48 54]
 [0 24 20]
 [0 29 79]
 [1 31 25]
 [0 54 101]
 [0 29 73]
 [1 35 24]
 [1 22 20]
 [0 23 54]
 [1 49 62]
 [0 31 43]
 [0 23 62]
 [0 45 54]
 [0 23 16]
 [0 63 65]
 [1 50 85]
 [1 32 137]
 [0 35 18]
 [1 19 48]
 [0 21 54]
 [0 38 67]
 [0 27 78]
 [1 28 87]
 [1 37 78]
 [1 18 59]
 [1 30 137]
 [0 35 19]
 

In [16]:
print(y_train)

[0 2 0 0 1 2 2 0 0 0 1 0 1 1 1 0 0 1 0 0 1 0 1 0 2 0 0 2 0 1 0 0 2 1 0 0 2
 0 2 1 0 2 2 0 2 2 1 0 0 0 2 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 2 1 0 1 0 0 0
 0 0 1 0 2 2 2 0 0 0 1 1 2 0 1 1 0 0 1 0 0 1 0 2 0 0 0 1 0 2 1 0 1 2 2 0 0
 1 1 2 1 2 2 0 0 1 1 0 0 0 0 2 1 0 0 1 1 0 2 2 2 1 0 2 0 0 0 2 1 1 0 0 2 0
 0 2]


In [17]:
print(X_test)

[[1 52 23]
 [1 40 87]
 [1 54 63]
 [1 48 61]
 [1 27 88]
 [1 46 98]
 [0 22 17]
 [1 48 77]
 [0 58 20]
 [0 44 78]
 [1 19 46]
 [0 31 70]
 [0 37 97]
 [0 47 78]
 [1 57 54]
 [0 23 18]
 [1 18 33]
 [1 47 71]
 [0 30 34]
 [1 59 54]
 [0 29 98]
 [1 28 77]
 [0 24 39]
 [0 30 78]
 [1 70 46]
 [1 39 69]
 [1 35 93]
 [1 30 99]
 [0 40 69]
 [0 49 39]
 [0 35 21]
 [1 47 43]
 [1 43 78]
 [0 19 63]
 [0 46 25]
 [0 36 103]
 [1 38 71]
 [0 31 17]
 [0 46 54]
 [0 66 63]
 [1 20 73]
 [0 43 48]
 [0 45 28]
 [1 19 64]
 [0 36 87]
 [0 54 47]
 [1 64 19]
 [1 26 54]
 [0 51 67]
 [0 32 76]]


In [18]:
print(y_test)

[2 2 0 0 0 2 1 0 2 2 0 1 0 2 0 1 1 2 1 0 1 1 0 1 0 1 1 1 0 2 0 0 2 0 2 1 1
 0 0 0 2 0 0 0 2 0 2 0 0 1]


## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:3] = sc.fit_transform(X_train[:, 1:3])
X_test[:, 1:3] = sc.transform(X_test[:, 1:3])

In [20]:
print(X_train)

[[0 0.5913187349407988 -0.4480388312716157]
 [0 -1.100849345970868 0.3417330313504265]
 [0 0.16827671471288216 1.4323703654475324]
 [0 -0.8188213324855901 -0.03434880799340313]
 [1 -0.32527230888635394 0.6425985028254902]
 [0 1.084867758540035 -1.237810693893658]
 [1 1.5079097787679516 -1.162594326024892]
 [0 1.225881765282674 0.6802066867598732]
 [0 1.860444795624549 -0.8617288545498283]
 [0 0.8733467484260766 -0.6360797509435305]
 [1 0.027262707970243272 0.37934121528480946]
 [0 0.5913187349407988 -0.03434880799340313]
 [0 -0.46628631562899286 1.3571539975787665]
 [0 -0.2547653055150345 -1.4258516135655728]
 [0 -0.043244295401076174 0.6425985028254902]
 [1 0.6618257383121183 -0.03434880799340313]
 [0 0.8028397450547572 -0.6736879348779135]
 [0 -0.5367933190003122 0.7554230546286391]
 [1 -0.3957793122576734 -0.7112961188122965]
 [0 1.1553747619113544 -0.14717335979655202]
 [0 -0.2547653055150345 0.49216576708795834]
 [0 2.071965805738507 -0.0719569919277861]
 [1 -0.46628631562899286 0

In [21]:
print(X_test)

[[1 0.9438537517973961 -1.4258516135655728]
 [1 0.09776971134156272 0.9810721582349369]
 [1 1.084867758540035 0.07847574380974576]
 [1 0.6618257383121183 0.003259375940979832]
 [1 -0.8188213324855901 1.0186803421693198]
 [1 0.5208117315694794 1.3947621815131495]
 [0 -1.1713563493421872 -1.6515007171718705]
 [1 0.6618257383121183 0.6049903188911072]
 [0 1.3668957720253128 -1.5386761653687215]
 [0 0.3797977248268405 0.6425985028254902]
 [1 -1.3828773594561456 -0.5608633830747646]
 [0 -0.5367933190003122 0.3417330313504265]
 [0 -0.11375129877239562 1.3571539975787665]
 [0 0.5913187349407988 0.6425985028254902]
 [1 1.2963887686539932 -0.2599979115997009]
 [0 -1.100849345970868 -1.6138925332374876]
 [1 -1.453384362827465 -1.0497697742217431]
 [1 0.5913187349407988 0.37934121528480946]
 [0 -0.6073003223716318 -1.0121615902873602]
 [1 1.437402775396632 -0.2599979115997009]
 [0 -0.6778073257429512 1.3947621815131495]
 [1 -0.7483143291142706 0.6049903188911072]
 [0 -1.0303423425995484 -0.824120

## Training the Random Forest Classification model on the Training set

In [22]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42,max_depth=5,class_weight='balanced')
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=5, n_estimators=10, random_state=42)

## Predicting a new result

## Predicting the Test set results

In [23]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [1 2]
 [0 0]
 [0 0]
 [1 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 1]
 [1 0]
 [2 2]
 [0 0]
 [1 1]
 [0 1]
 [0 2]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 2]
 [1 0]
 [0 0]
 [0 2]
 [0 0]
 [2 2]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [2 0]
 [0 0]
 [1 2]
 [0 0]
 [0 2]
 [0 0]
 [0 0]
 [1 1]]


## Making the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[18  4  1]
 [ 1 12  1]
 [ 4  2  7]]


0.74